name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Deploy to Backend Server
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: <backend_server_public_ip>
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/backend
            git pull
            npm install
            npm run build
            pm2 restart backend
